Add files via upload
added tip numeric input method. internally it has error below when access tip API. Wallet balance of the sender was changed property. Need to check does tip was thrown.

XMLHttpRequest : 200
tip_extention.js:79 textStatus     : parsererror
tip_extention.js:80 errorThrown    : Unexpected end of JSON input